# Generated by Django 3.2.5 on 2021-09-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolists',
            name='estimated_work_time',
            field=models.TimeField(),
        ),
    ]
