# Generated by Django 3.2.5 on 2021-09-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210924_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolists',
            name='is_work_finished',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolists',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolists',
            name='notifying_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
