# Generated by Django 3.2.5 on 2021-09-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210924_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='is_finished',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='notifying_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='is_all_day',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='notifying_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='is_hidden',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='friday_timetable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='monday_timetable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='saturday_timetable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='sunday_timetable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='thursday_timetable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='tuesday_timetable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='wednesday_timetable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolisttasks',
            name='is_work_finished',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
