# Generated by Django 3.2.5 on 2021-10-03 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210928_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolists',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subjects'),
        ),
    ]
