# Generated by Django 3.2.5 on 2021-10-03 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_todolists_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolists',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
